### PR TITLE
Add missing newline to the message

### PR DESCRIPTION
**Pull request by saper**

### CODE REVIEW

**Comment by BarraRoffe** [comment]
Thanks!

**Comment by saper** [comment]
thanks, are you guys accepting peering requests? not sure my message went through.

**Comment by BarraRoffe** [comment]
Yes, we do! Sorry, I was absent for a week and since the message expiry now works I probably missed your message. Could you please send a peering request to `7VW3oPLzQc7VS2anLyDtrdARDdSwa7QTF7h3N2t6J2VN_AjWZQfHoqK3yNqvXPkcswLNXSzFrCzJuRRKZKvY71UWT`? I need the URL of your server and the PeeringPublicKey. Please also add a repbin PubKey to your message where I can answer you.

**Comment by BarraRoffe** [comment]
Did you get my reply? You can also contact me via email at barraroffe@ownbay.net

**Pull request merged**
